module.exports = {
  SENDGRID_API_KEY: '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',
  // EMAIL TEMPATE IDS
  FROM_EMAIL: '',
  FROM_NAME: 'Canddidate',
  TEMPLATE_INVITE: '',
  TEMPLATE_SIGNUP_AND_INVITE: '',
  TEMPLATE_SIGNUP_USER: '',
  TEMPLATE_FORGET_PASSWORD: '',
  TEMPLATE_REMINDER: '',
  TEMPLATE_NOTIFICATION: ''
}
